name: Issue Statistics

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  issues: read
  pull-requests: read

jobs:
  issues-report:
    if: ${{ github.repository_owner == 'nrwl' }}
    runs-on: ubuntu-latest
    name: Report status
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.11.1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: '20.19.0'
          cache: 'pnpm'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          lookup-only: true
          path: '**/node_modules'
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2 # Needed since we are downloading artifact from a different workflow run, official actions/download-artifact doesn't support this.
        with:
          name: cached-issue-data
          path: ${{ github.workspace }}/scripts/issues-scraper/cached
          search_artifacts: true
        continue-on-error: true

      - name: Collect Issue Data
        id: collect
        run: npx tsx ./scripts/issues-scraper/index.ts
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: cached-issue-data
          path: ./scripts/issues-scraper/cached/data.json

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
        with:
          payload: ${{ steps.collect.outputs.SLACK_MESSAGE }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUES_REPORT_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
